var wql = `
  SELECT 
  workdayID,
  worker,
  legalNameInGeneralDisplayFormat, 
  preferredNameInGeneralDisplayFormat, 
  primaryHomeAddress{formattedAddressWithCountry as address} as homeAddress,
  hireDate,
  businessTitle as title,
  email_PrimaryHome as email_home,
  email_PrimaryWork as email_work,
  location,
  photo,
  costCenter
  FROM allWorkers
  (effectiveAsOfDate = '?')
    WHERE workdayID = '?'
`;

{
  "wql": wql
}